//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatchathraWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string Id { get; set; }
        public string RelatedDocumentIds { get; set; }
        public string ProjectId { get; set; }
        public string EnvironmentId { get; set; }
        public string Category { get; set; }
        public string UserId { get; set; }
        public string Username { get; set; }
        public System.DateTimeOffset Occurred { get; set; }
        public string Message { get; set; }
        public string JSON { get; set; }
    }
}
