//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatchathraWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPalTransaction
    {
        public int SeqNo { get; set; }
        public string RequestId { get; set; }
        public string TrackingReference { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public string RequestStatus { get; set; }
        public string TimeStamp { get; set; }
        public string RequestError { get; set; }
        public string Token { get; set; }
        public string PayerId { get; set; }
        public string RequestData { get; set; }
        public string PaymentTransactionId { get; set; }
        public string PaymentError { get; set; }
    }
}
