//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatchathraWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release
    {
        public string Id { get; set; }
        public string Version { get; set; }
        public System.DateTimeOffset Assembled { get; set; }
        public string ProjectId { get; set; }
        public string ProjectVariableSetSnapshotId { get; set; }
        public string ProjectDeploymentProcessSnapshotId { get; set; }
        public string JSON { get; set; }
    }
}
