//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatchathraWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string MemberUserIds { get; set; }
        public string ProjectIds { get; set; }
        public string EnvironmentIds { get; set; }
        public string JSON { get; set; }
    }
}
