//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MughapuWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPDETAIL
    {
        public int SHIPID { get; set; }
        public string SHIPTONAME { get; set; }
        public string SHIPTOSTREET { get; set; }
        public string SHIPTOCITY { get; set; }
        public string SHIPTOSTATE { get; set; }
        public string SHIPTOCOUNTRYCODE { get; set; }
        public string SHIPTOZIP { get; set; }
        public string SHIPTOCONTACTNO { get; set; }
        public string NOTESTOSELLER { get; set; }
        public string TrackingReference { get; set; }
    }
}
